{ config, lib, ... }:

let
  cfg = config.my.niri;
in
{
  imports = [
    ./input.nix
    ./layout.nix
    ./binds.nix
    ./window-rules.nix
    ./animations.nix
    ./misc.nix
  ];

  options.my.niri = {
    outputs = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "Per-host raw KDL block for `output` declarations.";
    };
    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra raw KDL appended at the end of niri config.";
    };
  };

  config = {
    # niri itself is enabled and packaged at the system level (modules/nixos/niri.nix); on the
    # home-manager side niri-flake auto-injects homeModules.config (via the nixos module's
    # home-manager.sharedModules), so programs.niri.config is available without an explicit import.
    # programs.niri.enable / .package are NixOS-only — do not set them here.
    programs.niri.config = lib.mkForce (lib.concatStringsSep "\n" [
      cfg._kdl.misc
      cfg._kdl.input
      cfg._kdl.layout
      cfg._kdl.animations
      cfg._kdl.windowRules
      cfg._kdl.binds
      cfg.outputs
      cfg.extraConfig
      ''
        // DMS-managed includes (auto-generated by DankMaterialShell)
        include "dms/cursor.kdl"
        include "dms/colors.kdl"
        include "dms/layout.kdl"
        include "dms/wpblur.kdl"
        include "dms/alttab.kdl"
        include "dms/binds.kdl"
        include "dms/outputs.kdl"
        include "dms/windowrules.kdl"
      ''
    ]);
  };
}
